### ISSUE TITLE
Jenv.ps1 use not working

### ISSUE THREAD

**Issue by treaz** [FelixSelter/JEnv-for-Windows#5]
in the same powershell session I'm dong the following
```
PS C:\Users\hconstantin> java -version
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
PS C:\Users\hconstantin> cd .\dev\
PS C:\Users\hconstantin\dev> .\jenv.ps1 use jdk11
Removed C:\Program Files\Java\jdk1.8.0_211\bin\ from path
Added C:\Program Files\Java\jdk-11.0.10\bin to the path
PS C:\Users\hconstantin\dev> java -version
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
PS C:\Users\hconstantin\dev>
```

I would expect that after .\jenv.ps1 use jdk11, the reported java version would be 11.
Note that I already tested jenv change jdk11 and that works as expected

**Comment by FelixSelter** [comment]
The vars aren't set via PowerShell  
It is expected that you run the batch script, not the PowerShell script.  
The batch file will run the PowerShell script which will create the temp files you mentioned in #7.  
Then the batch file will set the environment vars so that it also works for the parent shell.  
If I would set the vars in PowerShell and the script would be called from cmd then the vars would be set for the current PowerShell session which will terminate immidetaly.  

Maybe it would be a good idea to additionally set the values in PowerShell so if someone calls it within Powershell the values will be set too.  However, there will still be the temp files that are currently deleted by the batch file.  Probably we could add an optional argument to create the temp files which can be parsed by the batch file.  

I will look into this tomorrow. If you have any further suggestions please write below.  
For now, I would suggest using the batch file.

**Comment by treaz** [comment]
Thanks, Felix, I understood now, I was not using the script as expected.
Is there any reason to not move the script entirely to ps1? Keeping 2 files is cumbersome

**Comment by FelixSelter** [comment]
I know but two files are required. The jenv use command wont work else. If I would set the env vars only in Powershell the process will end when the ps1 script finishes and the vars would be gone.

If I would implement the above you can get rid of the batch file but you have to run all your commands in powershell.

I think it would be easier to put the files into C:/... Where they are out of sight. You can then call jenv from any console which should run the batch file.

I know its annoying but you cannot set the env vars of the parent shell. The child process inherits a copy of them and can only change the copy which wont affect the parent

**Comment by FelixSelter** [comment]
> 
> 
> Thanks, Felix, I understood now, I was not using the script as expected.
> Is there any reason to not move the script entirely to ps1? Keeping 2 files is cumbersome

Please refer to fa76a9c. I added some graphics that may be explained better why these files are required and visualize the hierarchies of the environment variables

**Comment by FelixSelter** [comment]
I pushed some updates. Can this be closed now?
